services:
  http-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: http-server-lab
    ports:
      - "8000:8000"
    volumes:
      - "./content:/app/content:ro"
      - "./concurrent_server.py:/app/concurrent_server.py:ro"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    stdin_open: true
    tty: true